### ISSUE TITLE
i18n generator problems

### ISSUE THREAD

**Issue by BorntraegerMarc** [matoilic/generator-angular-lazy#12]
Hi guys

At the moment i18n resources get generated like this:
`'my-test-component.foo': 'bar'`

Shouldn't it be like this?
`
myTestComponent: {foo: 'bar'}
`

With camel case and as an actual JSON object?

**Comment by BorntraegerMarc** [comment]
Just realized that the code is different when a state or component is generated. With a state the output is an actual JSON object. I believe it's a bug...

**Comment by matoilic** [comment]
Fixed. The translation files don't use actual objects to prevent a deep object structure. That improves readability for larger translation files and the lookup speed for keys is a bit faster, but that's just a detail.
