### ISSUE TITLE
Add Http2 and Service Worker support

### ISSUE THREAD

**Issue by BorntraegerMarc** [matoilic/generator-angular-lazy#17]
Hi guys

What do you think about adding a http2 option and basic service worker (https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) support? Think it would be awesome, if the app could be accessed offline by default. Also adding more service worker features for the individual generated projects would be way easier and more straight forward...

**Comment by matoilic** [comment]
HTTP2 is more something the server needs to support / provide including an optimised loading mechanism, e.g. analysing JS files for dependencies and sending them along with the originally requested file. SystemJS could provide information about dependencies using https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#depcache.

As for service workers, those are not generally needed by every project. Also, the number of use cases is broad and so the code that needs to be generated depends heavily on the goal you want to achieve with a worker. It's something that can be added using an additional generator but I don't see it as part of a **basic** setup.
