### ISSUE TITLE
After bundling, how to get it ready for deployment

### ISSUE THREAD

**Issue by SamarRizvi** [matoilic/generator-angular-lazy#29]
@matoilic @bdurrer I may be asking a noob question. But the index.html in build links to jspm_packages and config directories. How to have final build that can directly be deployed with only minified js (can be multiple), minified css (can be multiple) and an index.html.

**Comment by bdurrer** [comment]
After running the dist task, your folder is ready to be deployed. The task
creates bundles in your config file automatically (thats why you have to
revert the config after using the dist task or the hot-reload in serve mode
does not work anymore).

For my projects I had to bundle it into an java webapp, so I copied the
build,jspm and config folder (plus index.html) to my target folder using a
second task.

Am 07.10.2016 19:36 schrieb "Samar Rizvi" notifications@github.com:

**Comment by SamarRizvi** [comment]
@bdurrer My major concern is that in the **browser developer tools**, the **_components directory_** is automatically created probably due to `system.src.js`, and all of the js is readily and easily view-able by any developer, just the way it was coded (only difference that code is converted to ES5). Hence, if someone codes a full client based app, the uglifying and minifying shall be of no use. Can this be possible that what is minified remains minified.

**Comment by bdurrer** [comment]
@SamarRizvi 
Well, besides the fact that we are talking about security by obscurity:
I _think_ you could skip the whole build/component folder when uploading/packaging your project. Only the stuff in build/bundles is relevant for production (plus the static resources of course, which I keep outside of the component folders)

**Comment by SamarRizvi** [comment]
@bdurrer  , Even if you skip the components directory, due to some reason, probably, `system.src.js,` the components directory is internally created at runtime when the page loads. You can check in Sources section in Chrome dev tools.

**Comment by bdurrer** [comment]
@SamarRizvi, Chrome can show you the source because the dev tools load map files automatically.
These are generated automatically, even for the bundles. So just don't deploy the `*.map` files.

The components directory is created every time you run build. But when you deploy your project you can omit the folder build/components. You can simulate this by running bundle && serve and then delete the components folder before opening the page in the webbrowser. Also delete all `.map` files.

**Comment by SamarRizvi** [comment]
@bdurrer Thanks.

**Comment by SamarRizvi** [comment]
@bdurrer, any idea how to import a directive created through  `yo angular-lazy:directive` in another directory.

**Comment by bdurrer** [comment]
Your question could mean 
1. how can I use relative paths to import stuff in my JS
2. how can I create a directive in a specific folder

**one:** use a relative path in your import, eg `import myDirective from '../mydirective/index';`

**two:** Specify the prefix when creating it as [explained here](https://github.com/matoilic/generator-angular-lazy#directive-component). 
You can move an existing directive without breaking anything (well, you have to fix import statements of course). Unlike views, directives are self-contained and can be moved the old fashioned way.

@matoilic could be closed, the initial question was answered.

**Comment by SamarRizvi** [comment]
Well, It is a common directive to be used. Hence, I am using it as`import 'components/common/directives/sample-directive/index'` after creating it with `yo angular-lazy:directive --prefix "common/directives"`
