### ISSUE TITLE
Sourcemaps lost?

### ISSUE THREAD

**Issue by borntorun** [matoilic/generator-angular-lazy#3]
I'm using/experimenting the project and when I bundle it (gulp bundle) I realized that sourcemaps seem to be gone; can´t get the source for debugging.
I think something is wrong in the path for source map:  'build/the/component/path' relative to '/build/bundles' and the browser cannot resolve/get it.

The sourcemap is done on the build phase before bundling, is this correct?
Is this some "penalty" when using bundles?

Any ideas?
Thanks
![generator-angular-lazy-sourcmaps](https://cloud.githubusercontent.com/assets/820692/12885551/c2b4e354-ce5e-11e5-9dc2-6e8d5f997c09.jpg)

**Comment by matoilic** [comment]
This is a bug. Newer releases of SystemJS Builder seem to have made some improvements here. I'll update the bundler to use the latest version in the next release.

**Comment by matoilic** [comment]
0.5.0 should fix the source map paths. Unfortunately, only the transpiled sources can be mapped from the minified bundles at this point. This is due to limitations in SystemJS Builder.
