### ISSUE TITLE
Unable to create nested states

### ISSUE THREAD

**Issue by SamarRizvi** [matoilic/generator-angular-lazy#30]
@matoilic @bdurrer Here is my sample auth view for `auth-state`:

```
<div class="auth-content">
<div ui-view="authContent"></div>
</div>
```

Here is my auth-route:

```
import template from './auth-state.html!text';
import templateDefault from './auth-default.html!text';

function authRouteConfig($stateProvider) {
    $stateProvider
        .state('app.auth', {
            url: 'auth',
            views: {
                application: {
                    template
                },
                'authContent@application': {
                    controller: 'AuthStateController as authState',
                    templateDefault
                }
            }
        });
}

export default [
    '$stateProvider',
    authRouteConfig
];
```

And here is my register-route:

```
import template from './register-state.html!text';

function registerRouteConfig($stateProvider) {
    $stateProvider
        .state('app.auth.register', {
            url: 'register',
            views: {
                "authContent@application": {
                    controller: 'RegisterStateController as registerState',
                    template
                }
            }
        });
}

export default [
    '$stateProvider',
    registerRouteConfig
];
```

I am not not able to see the auth-default view inside https://localhost:8088/#/auth. Also when I traverse to https://localhost:8088/#/auth/register, I am redirected to https://localhost:8088/#/auth.

Am I doing something wrong?

**Comment by matoilic** [comment]
One issue I see is that the URL for `app.auth.register` is missing a leading slash. UI-Router doesn't put / in between routes automatically. Currently the URL for the registration page would look like https://localhost:8088/#/authregister.

**Comment by SamarRizvi** [comment]
No, it still redirects to auth. Try a simple 3 level nesting at your end. Secondly, why isn't `templateDefault` being shown when `auth`(https://localhost:8088/#/auth) is loaded?

**Comment by matoilic** [comment]
Nested views do work, I've already done several applications with 3 and 4 levels. But I have never used the "@" syntax. According to the UI-Router docs I think that you should use the state name after the "@" sign instead of the view name https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views#view-names---relative-vs-absolute-names

**Comment by SamarRizvi** [comment]
Do you have sample code or sample online demo app on which I can look at. Also, I first did it without '@', did not work.

**Comment by matoilic** [comment]
I've put together a quick example here https://github.com/matoilic/angular-nested-states-example

**Comment by SamarRizvi** [comment]
Thanks @matoilic Got it to work.
