### ISSUE TITLE
Include providers

### ISSUE THREAD

**Issue by ghost** [matoilic/generator-angular-lazy#4]
Hi there

Is there like a road map to include providers (https://docs.angularjs.org/guide/providers)? Also should the constants, services, etc. be defined in the component that's using them (for modularization) or should they be made available for the whole project?

cheerio

**Comment by matoilic** [comment]
The concept behind the generator is more to give you a starting point for a project and templates for the most common types of "components". A provider is a subpart of a component and usually only one file, so there is no real benefit of creating a generator for one file. 

When it comes to constants, I tend to put them in the component which uses them. If you want to make a redistributable and customizable component, then I usually make configurable services within those components. Constants shouldn't be used for configuration purposes across different applications. But again, that's more a question of taste.

**Comment by ghost** [comment]
Alright, thanks for the clarification :)
I'm going to close the issue...
