### ISSUE TITLE
Install error on windows 8

### ISSUE THREAD

**Issue by hoisel** [matoilic/generator-angular-lazy#6]
Hi, 
I'm getting the follwing error when installing on windows 8 machine:

> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-angular-lazy"
> npm ERR! node v4.3.1
> npm ERR! npm  v3.4.0
> npm ERR! path C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules\generator-angular-lazy
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall rename
> 
> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules\generator-angular-lazy' -> 'C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules.generator-angular-lazy.DELETE'
> npm ERR!     at Error (native)
> npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules\generator-angular-lazy' -> 'C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules.generator-angular-lazy.DELETE']
> npm ERR!   errno: -4048,
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'rename',
> npm ERR!   path: 'C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules\generator-angular-lazy',
> npm ERR!   dest: 'C:\Users\daniel.hoisel\AppData\Roaming\npm\node_modules\.generator-angular-lazy.DELETE' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\daniel.hoisel\Desktop\TEMP\generators-test\angular-lazy\npm-debug.log
> npm ERR! code 1

[npm-debug.log.txt](https://github.com/matoilic/generator-angular-lazy/files/163475/npm-debug.log.txt)

**Comment by matoilic** [comment]
This isn't an issue with the generator but one with NPM on Windows. In the past years I've had this issue every once in a while. This is a list of things that caused it for me in the past:
- I was using something other than the Windows standard shell, cmd.exe. **Solution:** do installations from the standard shell.
- The permissions on the NPM cache folder got messed up. **Solution:** run `npm cache clean` before `npm install`.
- Anti virus or other security related software locked some files in the NPM cache. **Solution:** restart PC. If the problem still arises, disable the related services to verify they're blocking the files. If it proves true, exclude the NPM cache directory from scanning / protection. Alternatively you can tell NPM to retry a file operation more often if it encounters a lock by setting `npm config set cache-lock-retries 1000` and `npm config set cache-lock-wait 100000`.
- Some installation scripts of sub-dependencies trip over spaces / special characters in the path of the NPM cache folder. **Solution:** change the cache location to a shorter and simpler path, e.g. `npm config set cache C:\dev\nodejs\npm-cache --global`.

**Comment by hoisel** [comment]
Thanks,
`npm cache clean` resolved for me!
