### ISSUE TITLE
Error when starting application for the first time

### ISSUE THREAD

**Issue by ghost** [matoilic/generator-angular-lazy#8]
Hi there

I initialized a new lazy project and everytime after I delete the build folder, I get the following error messages (when I start the application with 'gulp'):

`C:\Workspaces\Projects\jive\jive-app-recruting-management\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^`
`
Error: C:\Workspaces\Projects\jive\jive-app-recruting-management\node_modules\eslint-config-airbnb\rules\best-practices.js:
        Configuration for rule "no-labels" is invalid:
        Value "2,[object Object]" has more items than allowed.`

Are others also experiencing this problem?

**Comment by ghost** [comment]
The problem was a deprecated dependency. Updated gulp-eslint and it worked:
`"gulp-eslint": "^2.0.0",`

Thanks to @bdurrer ;)

**Comment by bdurrer** [comment]
Updating to `gulp-eslint 2.0.0` solves the issue and eslint runs again without crashing. 
However, the eslint rules seem to be way more restrictive now. Most gulp scripts are reported for minor issues.
